import{a as p,S,i as g}from"./assets/vendor-30VqbI-A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();p.defaults.baseURL="https://pixabay.com/api/";const u={key:"49355742-bd7d44539c0e651abd52850bf",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function m(s,t){u.q=s,u.page=t;try{return(await p.get(`?${new URLSearchParams(u)}`)).data}catch(o){return o}}const f=document.querySelector(".gallery"),a=document.querySelector(".loader"),y=new S(".gallery li a",{captionsData:"alt",captionDelay:250});function h(s){const t=s.map(o=>{const{webformatURL:c,tags:e,largeImageURL:r,likes:n,views:b,comments:L,downloads:w}=o;return`<li class="gallery-card">
        <a href="${r}">
          <img src="${c}" alt="${e}" class="card-image"  />
          <ul class="card-caption">
            <li class="image-tag"><p>Likes<br />${n}</p></li>
            <li class="image-tag"><p>Views<br />${b}</p></li>
            <li class="image-tag"><p>Comments<br />${L}</p></li>
            <li class="image-tag"><p>Downloads<br />${w}</p></li>
          </ul>
        </a>
      </li>`}).join("");f.insertAdjacentHTML("beforeend",t)}const P=document.querySelector(".form"),i=document.querySelector(".btn-load-js");i.style="display: none";a.classList.toggle("loader");let d="",l=1;P.addEventListener("submit",q);i.addEventListener("click",v);async function q(s){if(s.preventDefault(),d=s.currentTarget.elements.search_text.value.trim(),l=1,!d){g.error({message:"Search field must not be empty!",position:"topRight"});return}f.innerHTML="",a.classList.toggle("loader");try{const t=await m(d,l);if(t.totalHits===0){g.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.style="display: none";return}if(h(t.hits),t.totalHits<15){i.style="display: none";return}i.style="display: block"}catch{a.innerHTML="Oops... something went wrong"}finally{a.classList.toggle("loader"),y.refresh()}}async function v(){l+=1,a.classList.toggle("loader");const t=document.querySelector(".gallery>li").getBoundingClientRect().height;try{const o=await m(d,l);o.totalHits>15*l?(h(o.hits),scrollBy({top:t*2,behavior:"smooth"})):(i.style="display: none",g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.innerHTML="Oops... something went wrong"}finally{a.classList.toggle("loader"),y.refresh()}}
//# sourceMappingURL=index.js.map
